version: '3.9'

services:
  my_frontend:
    build:  ./Frontend
    env_file:
    - .env
    ports:
      - 7860:7860
    depends_on:
      - my_ollama
      - my_chroma_db
    networks:
    - take_home_network

  my_ollama:
    image: ollama/ollama:0.9.0
    ports:
      - 11434:11434
    networks:
    - take_home_network
  
  my_chroma_db:
    image: chromadb/chroma:1.0.12
    ports:
      - 8000:8000
    networks:
        - take_home_network
networks:
    take_home_network:
         name: take_home_network
